// Generated by CoffeeScript 1.12.4
(function() {
  var dragAndDrop,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  dragAndDrop = (function() {
    function dragAndDrop() {
      this.drop = bind(this.drop, this);
      this.drag = bind(this.drag, this);
      this.allowDrop = bind(this.allowDrop, this);
    }

    dragAndDrop.prototype.start = function() {
      this.bindEvents();
      this.allowDrop(ev);
      this.drag(ev);
      return this.drop(ev);
    };

    dragAndDrop.prototype.allowDrop = function(ev) {
      return ev.preventDefault();
    };

    dragAndDrop.prototype.drag = function(ev) {
      return ev.dataTransfer.setData('text', ev.target.id);
    };

    dragAndDrop.prototype.drop = function(ev) {
      var data;
      ev.preventDefault();
      data = ev.dataTransfer.getData('text');
      return ev.target.appendChild(document.getElementById(data));
    };

    dragAndDrop.prototype.bindEvents = function() {
      return $("#div1").on("click", function() {
        return console.log("HOla");
      });
    };

    return dragAndDrop;

  })();

  new dragAndDrop().start();

}).call(this);
